global:
  scrape_interval: 5s

scrape_configs:
- job_name: export485
  metrics_path: /metrics
  params:
    module: [epever_controller]
  static_configs:
    - targets:
      - 1
      - 5
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: localhost:9485
